### ISSUE TITLE
First install

### ISSUE THREAD

**Issue by liveweb22** [tonik/theme#110]
Hello! I've tried to install this theme, but it seems to return an error:

pm ERR! code 1
npm ERR! path /var/www/html/wp-content/themes/xweb/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c -- node scripts/build.js
npm ERR! Building: /usr/bin/node /var/www/html/wp-content/themes/xweb/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/var/www/html/wp-content/themes/xweb/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.7.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/var/www/html/wp-content/themes/xweb/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/var/www/html/wp-content/themes/xweb/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/var/www/html/wp-content/themes/xweb/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /var/www/html/wp-content/themes/xweb/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /var/www/html/wp-content/themes/xweb/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /var/www/html/wp-content/themes/xweb/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:211:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/var/www/html/wp-content/themes/xweb/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/var/www/html/wp-content/themes/xweb/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/var/www/html/wp-content/themes/xweb/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /var/www/html/wp-content/themes/xweb/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /var/www/html/wp-content/themes/xweb/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /var/www/html/wp-content/themes/xweb/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:211:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/var/www/html/wp-content/themes/xweb/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/var/www/html/wp-content/themes/xweb/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/var/www/html/wp-content/themes/xweb/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /var/www/html/wp-content/themes/xweb/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /var/www/html/wp-content/themes/xweb/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /var/www/html/wp-content/themes/xweb/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:211:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/var/www/html/wp-content/themes/xweb/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/var/www/html/wp-content/themes/xweb/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/var/www/html/wp-content/themes/xweb/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /var/www/html/wp-content/themes/xweb/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /var/www/html/wp-content/themes/xweb/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /var/www/html/wp-content/themes/xweb/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:211:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/var/www/html/wp-content/themes/xweb/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/var/www/html/wp-content/themes/xweb/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/var/www/html/wp-content/themes/xweb/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/var/www/html/wp-content/themes/xweb/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /var/www/html/wp-content/themes/xweb/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /var/www/html/wp-content/themes/xweb/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /var/www/html/wp-content/themes/xweb/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:211:21)
npm ERR! gyp ERR! System Linux 5.19.0-31-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/var/www/html/wp-content/themes/xweb/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /var/www/html/wp-content/themes/xweb/node_modules/node-sass
npm ERR! gyp ERR! node -v v18.7.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

**Comment by madebyaris** [comment]
Hi @liveweb22 ,
I'm not sure if this project 'still' alive, I suggest to use another framework if you are new with WP framework.

About your issue, it's might worth to check this https://github.com/tonik/theme/issues/107
